# Generated by Django 3.2.22 on 2023-10-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20231019_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='adjustment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='debit_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
