# Generated by Django 3.2.22 on 2023-10-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20231019_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recinvoice_item',
            name='description',
        ),
        migrations.AlterField(
            model_name='recinvoice',
            name='taxamount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
