# Generated by Django 3.2.22 on 2023-10-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_customer_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='is_converted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved')], default='Draft', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved'), ('Invoiced', 'Invoiced')], default='Draft', max_length=150),
        ),
    ]
