# Generated by Django 3.2.22 on 2023-10-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20231025_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankings_g',
            name='term',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='balance_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='loan_term',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='loan_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='loan_duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(max_length=30)),
                ('term_value', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='employee_loan_tran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_trans_date', models.CharField(max_length=100)),
                ('particular', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('intrest', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('balance_loan', models.IntegerField(blank=True, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('emploee_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeeloan')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee')),
            ],
        ),
    ]
