# Generated by Django 3.2.22 on 2023-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20231027_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankings_g',
            name='bank_status',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bankings_g',
            name='term',
            field=models.TextField(max_length=30),
        ),
    ]
