# Generated by Django 3.2.22 on 2023-10-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20231028_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoiceno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recinvoice',
            name='recinvoiceno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recinvoice',
            name='taxamount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
