# Generated by Django 4.2.3 on 2023-11-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0026_auto_20231031_1016"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="ref_no",
            field=models.CharField(default="", max_length=100),
        ),
    ]
