# Generated by Django 4.2.3 on 2023-11-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0028_remove_invoice_ref_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tot_inv_no",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
