# Generated by Django 4.2.3 on 2023-11-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0031_remove_invoice_gsttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="balance",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paidoff",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
