# Generated by Django 4.2.3 on 2023-11-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0032_invoice_balance_invoice_paidoff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice", name="duedate", field=models.DateField(),
        ),
    ]
