# Generated by Django 4.2.3 on 2023-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0035_invoice_bank_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="recinvoice",
            name="tot_inv_no",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
