# Generated by Django 4.2.3 on 2023-11-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0038_alter_recinvoice_adjust_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recinvoice",
            name="subtotal",
            field=models.FloatField(default=0, null=True),
        ),
    ]
