# Generated by Django 4.2.3 on 2023-11-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0039_alter_recinvoice_subtotal"),
    ]

    operations = [
        migrations.RemoveField(model_name="recinvoice", name="ordernumber",),
    ]
