# Generated by Django 4.2.3 on 2023-11-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0040_remove_recinvoice_ordernumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="recinvoice",
            name="entity_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
