# Generated by Django 4.2.3 on 2023-11-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0041_recinvoice_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recinvoice",
            name="enddate",
            field=models.DateField(default="", max_length=100),
        ),
    ]
