# Generated by Django 4.2.3 on 2023-11-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0042_alter_recinvoice_enddate"),
    ]

    operations = [
        migrations.RemoveField(model_name="recinvoice_item", name="items",),
        migrations.AlterField(
            model_name="recinvoice_item",
            name="product",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
