# Generated by Django 4.2.3 on 2023-11-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0043_remove_recinvoice_item_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recinvoice",
            name="enddate",
            field=models.DateField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="recinvoice",
            name="startdate",
            field=models.DateField(blank=True, default="", null=True),
        ),
    ]
