# Generated by Django 4.2.3 on 2023-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0044_alter_recinvoice_enddate_alter_recinvoice_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recinvoice",
            name="enddate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recinvoice",
            name="startdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
